using SeaHawkServices.Domain.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;
using static SeaHawkServices.Domain.Entities.Enums;

namespace Data
{
    public class AnalysisResult
    {
        public int Id { get; set; }
        public VesselDetail? VesselDetail { get; set; }
        public int? VesselDetailId { get; set; }
        public Company? Company { get; set; }
        public int? CompanyId { get; set; }
        public SampleCollections? SampleCollections { get; set; }
        public int? SampleCollectionsId { get; set; }
        public string? SampleNumber { get; set; }
        public string? ResultSummary { get; set; }
        public string? ReportLink { get; set; }
        public AnalysisResultStatus AnalysisResultStatus { get; set; }
        public DateTime? ResultDate { get; set; }
        public decimal? Density { get; set; }
        public string? DensityAss { get; set; }
        public decimal? CstAt40 { get; set; }
        public string? CstAr40Ass { get; set; }
        public decimal? CstAt50 { get; set; }
        public string? CstAt50Ass { get; set; }
        public decimal? CstAt80 { get; set; }
        public decimal? CstAt100 { get; set; }
        public decimal? Visc { get; set; }
        public decimal? ViscTemp { get; set; }
        public decimal? FlashPoint { get; set; }
        public string? FlashPointAss { get; set; }
        public string? PourPointSummStd { get; set; }
        public string? PourPointAss { get; set; }
        public decimal? CloudPoint { get; set; }
        public string? CloudPointAss { get; set; }
        public decimal? MCR { get; set; }
        public string? MCRAss { get; set; }
        public decimal? Ash { get; set; }
        public string? AshAss { get; set; }
        public decimal? Water { get; set; }
        public string? WaterAss { get; set; }
        public decimal? Sulphur { get; set; }
        public string? SulphurAss { get; set; }
        public decimal? SulphurPPM { get; set; }
        public string? SulphurPPMAss { get; set; }
        public string? Compatibility { get; set; }
        public decimal? Vanadium { get; set; }
        public string? VanadiumAss { get; set; }
        public decimal? Sodium { get; set; }
        public string? SodiumAss { get; set; }
        public decimal? Aluminum { get; set; }
        public decimal? Silicon { get; set; }
        public decimal? AlSi { get; set; }
        public string? AlSiAss { get; set; }
        public string? ULO { get; set; }
        public string? ULOAss { get; set; }
        public decimal? TSP { get; set; }
        public decimal? TSE { get; set; }
        public string? TSEAss { get; set; }
        public decimal? TSA { get; set; }
        public decimal? NetCalVal { get; set; }
        public decimal? CCAI { get; set; }
        public string? CCAIAss { get; set; }
        public decimal? Asphaltenes { get; set; }
        public decimal? Pb { get; set; }
        public decimal? Zn { get; set; }
        public string? ZnAss { get; set; }
        public decimal? Ca { get; set; }
        public string? CaAss { get; set; }
        public decimal? Mg { get; set; }
        public decimal? Ni { get; set; }
        public decimal? K { get; set; }
        public decimal? Li { get; set; }
        public decimal? Fe { get; set; }
        public string? Confirmation { get; set; }
        public decimal? Cr { get; set; }
        public decimal? Ant { get; set; }
        public string? AASS { get; set; }
        public decimal? Hg { get; set; }
        public decimal? Be { get; set; }
        public decimal? Co { get; set; }
        public decimal? Cu { get; set; }
        public decimal? Se { get; set; }
        public decimal? Cd { get; set; }
        public decimal? C { get; set; }
        public decimal? H { get; set; }
        public decimal? N { get; set; }
        public decimal? BSW { get; set; }
        public decimal? IBP { get; set; }
        public decimal? Pct10 { get; set; }
        public decimal? Pct20 { get; set; }
        public decimal? Pct30 { get; set; }
        public decimal? Pct40 { get; set; }
        public decimal? Pct50 { get; set; }
        public decimal? Pct90 { get; set; }
        public decimal? EP { get; set; }
        public decimal? Cetane { get; set; }
        public string? CetaneAss { get; set; }
        public string? Appearance { get; set; }
        public string? AppearanceAss { get; set; }
        public decimal? Sediment { get; set; }
        public decimal? BurningTemp { get; set; }
        public decimal? TotalAcid { get; set; }
        public string? TotalAcidAss { get; set; }
        public decimal? StrongAcid { get; set; }
        public decimal? Stability { get; set; }
        public decimal? GrossHeatComb { get; set; }
        public decimal? NetHeatComb { get; set; }
        public decimal? Neutrality { get; set; }
        public string? Grade { get; set; }
        public string? PortBunkered { get; set; }
        public DateTime? DateBunkered { get; set; }
        public string? SampleLocation { get; set; }
        public string? SealNumber { get; set; }
        public string? Supplier { get; set; }
        public DateTime? DateReceived { get; set; }
        public string? Laboratory { get; set; }
        public string? Technician { get; set; }
        public string? FuelType { get; set; }
        public string? BunkerReceipt { get; set; }
        public decimal? SupplierDensity { get; set; }
        public decimal? SupplierViscosity { get; set; }
        public decimal? PourPointWint { get; set; }
        public string? Initials { get; set; }
        public decimal? Halogens { get; set; }
        public decimal? H2S { get; set; }
        public string? H2SAss { get; set; }
        public decimal? P { get; set; }
        public string? PAss { get; set; }
        public string? Color { get; set; }
        public decimal? ColdFilterPluggingPoint { get; set; }
        public decimal? MineralAcidity { get; set; }
        public decimal? OxidationStability { get; set; }
        public string? OxidationStabilityAss { get; set; }
        public decimal? CopperCorrosion { get; set; }
        public DateTime? SampleSentOn { get; set; }
        public string? AirwayNumber { get; set; }
        public string? SealNumberSupplier { get; set; }
        public string? SealNumberRetained { get; set; }
        public string? SealNumberMARPOL { get; set; }
        public string? FuelMixWithFuelOnboard { get; set; }
        public decimal? ShippingCharges { get; set; }
        public string? SampleSentFrom { get; set; }
        public string? TankNumber { get; set; }
        public DateTime? SampleReportDate { get; set; }
        public string? SampleMethod { get; set; }
        public decimal? MCR10 { get; set; }
        public decimal? FTIR { get; set; }
        public string? FTIRAss { get; set; }
        public decimal? WaterKarlFischer { get; set; }
        public decimal? Demulsification { get; set; }
        public decimal? ParticulateContamination { get; set; }
        public string? ParticulateAss { get; set; }
        public decimal? FreeGlycerin { get; set; }
        public decimal? TotalGlycerin { get; set; }
        public decimal? Lubricity { get; set; }
        public string? LubricityAss { get; set; }
        public string? ClientRefNumber { get; set; }
        public decimal? DieselRangeOrganics { get; set; }
        public decimal? APIGravity { get; set; }
        public decimal? DistResLoss { get; set; }
        public decimal? InjTemp10cst { get; set; }
        public decimal? InjTemp13cst { get; set; }
        public decimal? InjTemp15cst { get; set; }
        public decimal? MPT100cst { get; set; }
        public decimal? NaVRatio { get; set; }
        public decimal? NaK { get; set; }
        public string? BunkerTanker { get; set; }
        public int? FuelTypeID { get; set; }
        public decimal? SupplierSulphur { get; set; }
        public string? TestType { get; set; }
        public decimal? NetSpecificEnergy { get; set; }
        public string? Polymer { get; set; }
        public decimal? TotalDeposits { get; set; }
        public int? OrderID { get; set; }
        public decimal? SupplierSulfur { get; set; }
        public decimal? SSQuantity { get; set; }
        public decimal? InjTemp12cst { get; set; }
        public decimal? InjTemp14cst { get; set; }
        public string? Comment { get; set; }
        public string? Specification { get; set; }
        public decimal? InjTemp20cst { get; set; }
        public decimal? InjTemp25cst { get; set; }
        public string? OffSpec1 { get; set; }
        public string? OffSpec2 { get; set; }
        public string? OffSpec3 { get; set; }
        public string? OffSpec4 { get; set; }
        public decimal? QuantityDiff { get; set; }
        public decimal? SupplierSulfurPPM { get; set; }
        public string? Comment1 { get; set; }
        public string? Comment2 { get; set; }
        public string? Comment3 { get; set; }
        public string? Comment4 { get; set; }
        public string? Comment5 { get; set; }
        public string? Comment6 { get; set; }
        public string? ASSESS { get; set; }
        public string? LID { get; set; }
        public string? FileName { get; set; }
    }
}
