// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeaHawkServices.Infrastructure.Data;

#nullable disable

namespace SeaHawkServices.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250820132709_UpdateTable_SampleCollection")]
    partial class UpdateTable_SampleCollection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.AnalysisResults", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateBunkered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateReceived")
                        .HasColumnType("datetime2");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortBunkered")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SampleNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VesselDetailsId")
                        .HasColumnType("int");

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("VesselDetailsId");

                    b.ToTable("AnalysisResults");
                });

            modelBuilder.Entity("Data.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Charterer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractLab")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaxArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaxCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaxNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelSupplier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipOwner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateOrProvince")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Data.CompanyUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("CompanyUser");
                });

            modelBuilder.Entity("Data.SampleCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AWBNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualDeliveryCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualDeliveryCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualDeliveryCountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActualDeliveryResidential")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgentEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ConsigneeCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsigneeCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsigneeCountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsigneeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsigneePostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsigneeResidential")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsigneeStateCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Country")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CurrentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAttempts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryLocationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliverySignatureName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationServiceAreaCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationServiceAreaDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DlvyNotificationFlag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuplicateWaybill")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailCC1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailCC2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailCC3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstimatedDeliveryDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlobalProductCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMONumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoOfSamples")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginServiceAreaCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginServiceAreaDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherIdentifiersType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherIdentifiersValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageDimensionsHeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageDimensionsLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageDimensionsUnits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageDimensionsWidth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageWeightUnits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageWeightValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackagingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickupAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pieces")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PreferredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreferredTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestorEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipmentDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipmentWeightUnits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipmentWeightValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipperAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipperCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipperCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipperCountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipperName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipperPostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipperReferenceID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipperResidential")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipperStateCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialHandlingsDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialHandlingsPaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialHandlingsType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusDetailCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusDetailCreationTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusDetailDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusDetailLocationCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusDetailLocationCountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusDetailLocationCountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusDetailLocationResidential")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Town")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackingNumberUniqueIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VesselName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeightUnit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedUserId");

                    b.ToTable("SampleCollection");
                });

            modelBuilder.Entity("Data.VesselDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Built")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ByEMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ByFax")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ByTelex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallSign")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Charterer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommissionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOGrade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DOReportType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diesel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Draft")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dwt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExVesselName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FOReportType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaxArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaxCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaxNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Filter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelSystem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GOGrade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneratorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HFO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HFOGrade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IFO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IFOGrade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMONumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Propulsion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Registry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TlxNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VesselDetails");
                });

            modelBuilder.Entity("Data.VesselUsers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IMONumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VesselDetailsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VesselDetailsId");

                    b.ToTable("VesselUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SeaHawkServices.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SeaHawkServices.Domain.Entities.MSCAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AASS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("APIGravity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ASSESS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AirwayNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AlSi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AlSiAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Aluminum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Appearance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AppearanceAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AshAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Asphaltenes")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal?>("BSW")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Be")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BunkerReceipt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BunkerTanker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("BurningTemp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("C")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CCAI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CCAIAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ca")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CaAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cetane")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CetaneAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClientRefNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CloudPoint")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CloudPointAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Co")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ColdFilterPluggingPoint")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Color")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Compatibility")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Confirmation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CopperCorrosion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Cu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DateBunkered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateReceived")
                        .HasColumnType("datetime2");

                    b.Property<string>("Demulsification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Density")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DensityAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DieselRangeOrganics")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DistResLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FTIR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FTIRAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Fe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FlashPoint")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("FlashPointAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FreeGlycerin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("FuelMixWithFuelOnboard")
                        .HasColumnType("bit");

                    b.Property<string>("FuelType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelTypeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GrossHeatComb")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("H")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("H2S")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("H2SAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Halogens")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Hg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("IBP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Initials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("InjTemp10cst")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InjTemp12cst")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InjTemp13cst")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InjTemp14cst")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InjTemp15cst")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InjTemp20cst")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InjTemp25cst")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("K")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Laboratory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Li")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Lubricity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LubricityAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MCR")
                        .HasColumnType("decimal(5,3)");

                    b.Property<decimal?>("MCR10")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal?>("MCRAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MPT100cst")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Mg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MineralAcidity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("N")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NaK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NaVRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NetCalVal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NetHeatComb")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NetSpecificEnergy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Neutrality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Ni")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OffSpec1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OffSpec2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OffSpec3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OffSpec4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OxidationStability")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OxidationStabilityAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("P")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ParticulateAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ParticulateContamination")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal?>("Pb")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Polymer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PortBunkered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PourPointAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PourPointSummStd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PourPointWint")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("QuantityDiff")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SSQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SampleLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SampleMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SampleNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SampleReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SampleSentFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SampleSentOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Se")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SealNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SealNumberMARPOL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SealNumberRetained")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SealNumberSupplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Sediment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ShippingCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Silicon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Sodium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SodiumAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Specification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("StrongAcid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Sulphur")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SulphurAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SulphurPPM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SulphurPPMAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SupplierDensity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SupplierSulfur")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SupplierSulfurPPM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SupplierSulphur")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SupplierViscosity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TSA")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal?>("TSE")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal?>("TSEAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TSP")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("TankNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Technician")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalAcid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalAcidAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalDeposits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalGlycerin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ULO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ULOAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VISC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VISCTEMP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Vanadium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VanadiumAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VesselName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Water")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("WaterAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("WaterKarlFischer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Zn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ZnAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("cstAr40Ass")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("cstAt100")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("cstAt40")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal?>("cstAt50")
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal?>("cstAt50Ass")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("cstAt80")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("pct10")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("pct20")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("pct30")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("pct40")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("pct50")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("pct90")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MSCAnalysis");
                });

            modelBuilder.Entity("SeaHawkServices.Domain.StoredProcedures.DistillateRow", b =>
                {
                    b.Property<decimal?>("ASSESS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Appearance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AppearanceAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AshAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BunkerTanker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Cetane")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CetaneAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CloudPoint")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CloudPointAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateBunkered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateReceived")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Density")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DensityAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FTIR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FTIRAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FlashPoint")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FlashPointAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FuelType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("H2S")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("H2SAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Laboratory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Lubricity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LubricityAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MCR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MCRAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OxidationStability")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OxidationStabilityAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ParticulateAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ParticulateContamination")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PortBunkered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PourPointAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PourPointSummStd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SampleLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SampleNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SampleReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SealNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SulphurPPM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SulphurPPMAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SupplierDensity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SupplierSulfurPPM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SupplierViscosity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalAcid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalAcidAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VesselName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Water")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("WaterAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("cstAr40Ass")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("cstAt40")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("SeaHawkServices.Domain.StoredProcedures.ResidualRow", b =>
                {
                    b.Property<decimal?>("ASSESS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AlSi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AlSiAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AshAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BunkerTanker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CCAI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CCAIAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ca")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CaAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateBunkered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateReceived")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Density")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DensityAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FlashPoint")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FlashPointAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FuelType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("H2S")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("H2SAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Laboratory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MCR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MCRAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("P")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PortBunkered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PourPointAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PourPointSummStd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SampleLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SampleNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SampleReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SealNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Sodium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SodiumAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Sulphur")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SulphurAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SupplierDensity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SupplierSulphur")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SupplierViscosity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TSE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TSEAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalAcid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalAcidAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ULO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ULOAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Vanadium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VanadiumAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VesselName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Water")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("WaterAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Zn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ZnAss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("cstAt50")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("cstAt50Ass")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Data.AnalysisResults", b =>
                {
                    b.HasOne("Data.VesselDetails", "VesselDetails")
                        .WithMany()
                        .HasForeignKey("VesselDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VesselDetails");
                });

            modelBuilder.Entity("Data.CompanyUser", b =>
                {
                    b.HasOne("Data.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeaHawkServices.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.SampleCollection", b =>
                {
                    b.HasOne("Data.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeaHawkServices.Domain.Entities.ApplicationUser", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("CreatedUser");
                });

            modelBuilder.Entity("Data.VesselUsers", b =>
                {
                    b.HasOne("Data.VesselDetails", "VesselDetails")
                        .WithMany()
                        .HasForeignKey("VesselDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VesselDetails");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SeaHawkServices.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SeaHawkServices.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeaHawkServices.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SeaHawkServices.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
