using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SeaHawkServices.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class UpdateAnalysisResult : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AnalysisResults");

            migrationBuilder.CreateTable(
                name: "AnalysisResult",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    VesselDetailId = table.Column<int>(type: "int", nullable: true),
                    VDId = table.Column<int>(type: "int", nullable: true),
                    SampleNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Density = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    DensityAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CstAt40 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CstAr40Ass = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CstAt50 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CstAt50Ass = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CstAt80 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CstAt100 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Visc = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    ViscTemp = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    FlashPoint = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    FlashPointAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PourPointSummStd = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PourPointAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CloudPoint = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CloudPointAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MCR = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    MCRAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Ash = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    AshAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Water = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    WaterAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Sulphur = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    SulphurAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SulphurPPM = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    SulphurPPMAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Compatibility = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Vanadium = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    VanadiumAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Sodium = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    SodiumAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Aluminum = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Silicon = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    AlSi = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    AlSiAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ULO = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ULOAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TSP = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TSE = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TSEAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TSA = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    NetCalVal = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CCAI = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CCAIAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Asphaltenes = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Pb = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Zn = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    ZnAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Ca = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CaAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Mg = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Ni = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    K = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Li = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Fe = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Confirmation = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Cr = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Ant = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    AASS = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Hg = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Be = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Co = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Cu = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Se = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Cd = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    C = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    H = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    N = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    BSW = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    IBP = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Pct10 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Pct20 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Pct30 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Pct40 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Pct50 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Pct90 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    EP = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Cetane = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CetaneAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Appearance = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AppearanceAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Sediment = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    BurningTemp = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TotalAcid = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TotalAcidAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    StrongAcid = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Stability = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    GrossHeatComb = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    NetHeatComb = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Neutrality = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Grade = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PortBunkered = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DateBunkered = table.Column<DateTime>(type: "datetime2", nullable: true),
                    SampleLocation = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SealNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Supplier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DateReceived = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Laboratory = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Technician = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FuelType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BunkerReceipt = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SupplierDensity = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    SupplierViscosity = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    PourPointWint = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Initials = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Halogens = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    H2S = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    H2SAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    P = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    PAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Color = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ColdFilterPluggingPoint = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    MineralAcidity = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    OxidationStability = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    OxidationStabilityAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CopperCorrosion = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    SampleSentOn = table.Column<DateTime>(type: "datetime2", nullable: true),
                    AirwayNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SealNumberSupplier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SealNumberRetained = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SealNumberMARPOL = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FuelMixWithFuelOnboard = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ShippingCharges = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    SampleSentFrom = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TankNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SampleReportDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    SampleMethod = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MCR10 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    FTIR = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    FTIRAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WaterKarlFischer = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Demulsification = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    ParticulateContamination = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    ParticulateAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FreeGlycerin = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TotalGlycerin = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Lubricity = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    LubricityAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ClientRefNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DieselRangeOrganics = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    APIGravity = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    DistResLoss = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    InjTemp10cst = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    InjTemp13cst = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    InjTemp15cst = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    MPT100cst = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    NaVRatio = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    NaK = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    BunkerTanker = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FuelTypeID = table.Column<int>(type: "int", nullable: true),
                    SupplierSulphur = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TestType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NetSpecificEnergy = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Polymer = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TotalDeposits = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    OrderID = table.Column<int>(type: "int", nullable: true),
                    SupplierSulfur = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    SSQuantity = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    InjTemp12cst = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    InjTemp14cst = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Comment = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Specification = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InjTemp20cst = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    InjTemp25cst = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    OffSpec1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OffSpec2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OffSpec3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OffSpec4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    QuantityDiff = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    SupplierSulfurPPM = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Comment1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Comment2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Comment3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Comment4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Comment5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Comment6 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ASSESS = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    LID = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FileName = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AnalysisResult", x => x.Id);
                    table.ForeignKey(
                        name: "FK_AnalysisResult_VesselDetail_VesselDetailId",
                        column: x => x.VesselDetailId,
                        principalTable: "VesselDetail",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateIndex(
                name: "IX_AnalysisResult_VesselDetailId",
                table: "AnalysisResult",
                column: "VesselDetailId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AnalysisResult");

            migrationBuilder.CreateTable(
                name: "AnalysisResults",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    VesselDetailId = table.Column<int>(type: "int", nullable: true),
                    AASS = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    APIGravity = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    ASSESS = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AirwayNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AlSi = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    AlSiAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Aluminum = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Ant = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Appearance = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AppearanceAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Ash = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    AshAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Asphaltenes = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    BSW = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Be = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    BunkerReceipt = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BunkerTanker = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    BurningTemp = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    C = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CCAI = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CCAIAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Ca = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CaAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Cd = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Cetane = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CetaneAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ClientRefNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CloudPoint = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CloudPointAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Co = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    ColdFilterPluggingPoint = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Color = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Comment = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Comment1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Comment2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Comment3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Comment4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Comment5 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Comment6 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Compatibility = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Confirmation = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CopperCorrosion = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Cr = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CstAr40Ass = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CstAt100 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CstAt40 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CstAt50 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    CstAt50Ass = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CstAt80 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Cu = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    DateBunkered = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DateReceived = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Demulsification = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Density = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    DensityAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DieselRangeOrganics = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    DistResLoss = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    EP = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    FTIR = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    FTIRAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Fe = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    FileName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FlashPoint = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    FlashPointAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FreeGlycerin = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    FuelMixWithFuelOnboard = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FuelType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FuelTypeID = table.Column<int>(type: "int", nullable: true),
                    Grade = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    GrossHeatComb = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    H = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    H2S = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    H2SAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Halogens = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Hg = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    IBP = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Initials = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InjTemp10cst = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    InjTemp12cst = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    InjTemp13cst = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    InjTemp14cst = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    InjTemp15cst = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    InjTemp20cst = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    InjTemp25cst = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    K = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    LID = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Laboratory = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Li = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Lubricity = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    LubricityAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MCR = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    MCR10 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    MCRAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MPT100cst = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Mg = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    MineralAcidity = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    N = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    NaK = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    NaVRatio = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    NetCalVal = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    NetHeatComb = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    NetSpecificEnergy = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Neutrality = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Ni = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    OffSpec1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OffSpec2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OffSpec3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OffSpec4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OrderID = table.Column<int>(type: "int", nullable: true),
                    OxidationStability = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    OxidationStabilityAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    P = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    PAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ParticulateAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ParticulateContamination = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Pb = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Pct10 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Pct20 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Pct30 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Pct40 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Pct50 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Pct90 = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Polymer = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PortBunkered = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PourPointAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PourPointSummStd = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PourPointWint = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    QuantityDiff = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    SSQuantity = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    SampleLocation = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SampleMethod = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SampleNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SampleReportDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    SampleSentFrom = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SampleSentOn = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Se = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    SealNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SealNumberMARPOL = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SealNumberRetained = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SealNumberSupplier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Sediment = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    ShippingCharges = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Silicon = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Sodium = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    SodiumAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Specification = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Stability = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    StrongAcid = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Sulphur = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    SulphurAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SulphurPPM = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    SulphurPPMAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Supplier = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SupplierDensity = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    SupplierSulfur = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    SupplierSulfurPPM = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    SupplierSulphur = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    SupplierViscosity = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TSA = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TSE = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TSEAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TSP = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TankNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Technician = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TestType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TotalAcid = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TotalAcidAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TotalDeposits = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    TotalGlycerin = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    ULO = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ULOAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    VDId = table.Column<int>(type: "int", nullable: true),
                    Vanadium = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    VanadiumAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Visc = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    ViscTemp = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Water = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    WaterAss = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    WaterKarlFischer = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    Zn = table.Column<decimal>(type: "decimal(18,2)", nullable: true),
                    ZnAss = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AnalysisResults", x => x.Id);
                    table.ForeignKey(
                        name: "FK_AnalysisResults_VesselDetail_VesselDetailId",
                        column: x => x.VesselDetailId,
                        principalTable: "VesselDetail",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateIndex(
                name: "IX_AnalysisResults_VesselDetailId",
                table: "AnalysisResults",
                column: "VesselDetailId");
        }
    }
}
